name: NaacServer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  get-token:
    name: Get Registration Token
    runs-on: ubuntu-latest

    steps:
      - name: Get registration token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TOKEN=$(curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/SurajSinghDevloper/NaacServer/actions/runners/registration-token | jq -r .token)
          echo "Registration Token: $TOKEN"
          echo "::set-output name=regToken::$TOKEN"

  build:

    runs-on: ubuntu-latest

    needs: get-token

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package -e -X

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      # - name: Update dependency graph
        # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
        # with:
         #  registration-token: ${{ needs.get-token.outputs.regToken }}
